version: '2'

services:
  zookeeper:
    image: registry.drycc.cc/drycc-addons/zookeeper:3.7.1
    ports:
      - '2181'
    volumes:
      - zookeeper_data:/drycc
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  zookeeper2:
    image: registry.drycc.cc/drycc-addons/zookeeper:3.7.1
    ports:
      - '2181'
    volumes:
      - zookeeper2_data:/drycc
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  zookeeper3:
    image: registry.drycc.cc/drycc-addons/zookeeper:3.7.1
    ports:
      - '2181'
    volumes:
      - zookeeper3_data:/drycc
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888

volumes:
  zookeeper_data:
    driver: local
  zookeeper2_data:
    driver: local
  zookeeper3_data:
    driver: local
