version: '2'

services:
  zookeeper:
    image: registry.drycc.cc/drycc-addons/zookeeper:3.7.1
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/drycc/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  zookeeper_data:
    driver: local
